- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Delete App Old Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download & Extract {{component}} App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes